// Auto-generated by stellar-contracts-kit
// Contract : CAFBSSDUIFAHPTJJW4MCESAQKYBSUCGE6J4WPLZYBBQVGT6XXU3JPZTD
// Network  : testnet
// Re-run `npx sck generate` to update after a contract upgrade.

import type { ContractMethodFn } from 'stellar-contracts-kit'

// Contract Interface

export interface MBGContract {
  get_mie: ContractMethodFn<number, []>
  vote_mie: ContractMethodFn<void, []>
  get_bakso: ContractMethodFn<number, []>
  get_esteh: ContractMethodFn<number, []>
  get_geprek: ContractMethodFn<number, []>
  vote_bakso: ContractMethodFn<void, []>
  vote_esteh: ContractMethodFn<void, []>
  vote_geprek: ContractMethodFn<void, []>
}

export const CONTRACT_ID = 'CAFBSSDUIFAHPTJJW4MCESAQKYBSUCGE6J4WPLZYBBQVGT6XXU3JPZTD' as const
