// Auto-generated by stellar-contracts-kit
// Example usage for MBGContract
// Contract : CAFBSSDUIFAHPTJJW4MCESAQKYBSUCGE6J4WPLZYBBQVGT6XXU3JPZTD
// Network  : testnet
// Adapt this file to your project. Re-run `npx sck generate` to refresh after a contract upgrade.

import { StellarContractsKit } from 'stellar-contracts-kit'
// Types file: ./contracts/mbgcontract.ts. Update the path below if using snippets elsewhere.
import type { MBGContract } from './mbgcontract.js'
import { CONTRACT_ID } from './mbgcontract.js'

const kit = new StellarContractsKit({ network: 'testnet' })

// Connect wallet (opens picker modal if no wallet specified)
const { address } = await kit.connect()
console.log('Connected:', address)

// Load the typed contract client
const contract = await kit.contract<MBGContract>(CONTRACT_ID)

// get_mie() -> number
const { result: get_mieResult } = await contract.get_mie.read()
console.log('get_mie:', get_mieResult)

// vote_mie() -> void
const { txHash: vote_mieTxHash } = await contract.vote_mie.invoke()
console.log('vote_mie txHash:', vote_mieTxHash)

// get_bakso() -> number
const { result: get_baksoResult } = await contract.get_bakso.read()
console.log('get_bakso:', get_baksoResult)

// get_esteh() -> number
const { result: get_estehResult } = await contract.get_esteh.read()
console.log('get_esteh:', get_estehResult)

// get_geprek() -> number
const { result: get_geprekResult } = await contract.get_geprek.read()
console.log('get_geprek:', get_geprekResult)

// vote_bakso() -> void
const { txHash: vote_baksoTxHash } = await contract.vote_bakso.invoke()
console.log('vote_bakso txHash:', vote_baksoTxHash)

// vote_esteh() -> void
const { txHash: vote_estehTxHash } = await contract.vote_esteh.invoke()
console.log('vote_esteh txHash:', vote_estehTxHash)

// vote_geprek() -> void
const { txHash: vote_geprekTxHash } = await contract.vote_geprek.invoke()
console.log('vote_geprek txHash:', vote_geprekTxHash)
